#! /bin/bash

CLASSPATH=bin:src:lib/clojure-1.0.0.jar:lib/clojure-contrib.jar:lib/jline-0.9.94.jar
if [ -z "$1" ]; then 
     java -cp $CLASSPATH \
          jline.ConsoleRunner clojure.lang.Repl    
else
     java -cp $CLASSPATH clojure.lang.Script $1
fi